# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16, verbose_name='Senha')),
                ('cpfCpnj', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
    ]
