# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('preco', models.FloatField(null=True, verbose_name='Preço')),
                ('imagem_principal', models.ImageField(null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte')),
            ],
            options={
                'verbose_name_plural': 'Artes',
                'verbose_name': 'Arte',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, null=True, verbose_name='Categoria da arte')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte')),
                ('dataImagem', models.DateTimeField(auto_now_add=True, verbose_name='Data da imagem')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('idArte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Arte')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'verbose_name': 'Imagem',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=15, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=15, null=True, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16, null=True, verbose_name='Senha')),
                ('cpfCpnj', models.CharField(max_length=11, null=True, verbose_name='CPF')),
            ],
        ),
        migrations.AddField(
            model_name='arte',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
        migrations.AddField(
            model_name='arte',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
