# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('preco', models.FloatField(blank=True, null=True, verbose_name='Preço')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte')),
            ],
            options={
                'verbose_name_plural': 'Artes',
                'verbose_name': 'Arte',
            },
        ),
        migrations.CreateModel(
            name='cartaoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=16, null=True, verbose_name='Número de cartão')),
                ('codSeguranca', models.CharField(max_length=3, null=True, verbose_name='Código de segurança')),
                ('nomeCartao', models.CharField(max_length=40, null=True, verbose_name='Nome')),
                ('dataValidade', models.DateField(verbose_name='Data Vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, null=True, verbose_name='Categoria da arte')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfCnpj', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('cartao', models.ManyToManyField(blank=True, to='core.cartaoCredito')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='arte',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
        migrations.AddField(
            model_name='arte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
