# Generated by Django 2.0 on 2017-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='imagem_principal',
            field=models.ImageField(null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte'),
        ),
    ]
