# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataImagem', models.DateTimeField(auto_now_add=True, verbose_name='Data da imagem')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('idArte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Arte')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpfCpnj',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=16, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='arte',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
