# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arte_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='user',
        ),
    ]
