# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171213_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cpfCpnj',
            new_name='cpfCnpj',
        ),
    ]
