# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171128_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arte',
            options={'verbose_name': 'Arte', 'verbose_name_plural': 'Artes'},
        ),
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AddField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte'),
        ),
    ]
