# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens',
            name='idArte',
        ),
        migrations.AlterField(
            model_name='arte',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='img/imagensArtes/', verbose_name='Imagem da Arte'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='preco',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Número de cartão'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpfCnpj',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=30, primary_key=True, serialize=False, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Senha'),
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
