# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171129_0058'),
        ('core', '0003_auto_20171129_1125'),
    ]

    operations = [
    ]
