# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20171202_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=15, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=15, null=True, verbose_name='Sobrenome'),
        ),
    ]
