# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171202_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
